team_codes = {
    'Georgia Tech Yellow':'Georgia Tech',
    'Nevada Wolf':'Nevada',
    'Hawaii Rainbow':'Hawaii',
    'Rutgers Scarlet':'Rutgers',
    'Wake Forest Demon':'Wake Forest',
    'Army Black':'Army',
    'Lehigh Mountain':'Lehigh',
    'Duke Blue':'Duke',
    'Kent State Golden':'Kent State',
    'Penn State Nittany':'Penn State',
    'Miami':'Miami (FL)',
    'North Dakota Fighting':'North Dakota',
    'California Golden':'California',
    'Marshall Thundering':'Marshall',
    'North Texas Mean':'North Texas',
    'Campbell Fighting':'Campbell',
    'Alabama Crimson':'Alabama',
    'UNLV':'Nevada-Las Vegas',
    'Middle Tennessee Blue':'Middle Tennessee State',
    'Tennessee Tech Golden':'Tennessee Tech',
    'Texas Tech Red':'Texas Tech',
    'Notre Dame Fighting':'Notre Dame',
    'Louisiana Ragin':'Louisiana',
    'Pittsburgh':'Pitt',
    'Tulane Green':'Tulane',
    'Minnesota Golden':'Minnesota',
    'Gardner-Webb Runnin':'Gardner-Webb',
    'Tulsa Golden':'Tulsa',
    'Illinois Fighting':'Illinois',
    'UL Monroe':'Louisiana-Monroe',
    'St Louis Blues':'St. Louis Blues',
    'Montréal Canadiens':'Montreal Canadiens',
    'Maine Black':'Maine',
    'Charleston':'College of Charleston',
    'Marist Red':'Marist',
    'South Dakota St':'South Dakota State',
    'McNeese':'McNeese State',
    'Texas A&M-CC':'Texas A&M-Corpus Christi',
    'Appalachian St':'Appalachian State',
    'St. John\'s Red':'St. John\'s (NY)',
    'Missouri St':'Missouri State',
    'Arkansas-Pine Bluff Golden':'Arkansas-Pine Bluff',
    'Georgia St':'Georgia State',
    'CSU Northridge':'Cal State Northridge',
    'Florida St':'Florida State',
    'Wright St':'Wright State',
    'Morehead St':'Morehead State',
    'Michigan St':'Michigan State',
    'Indiana St':'Indiana State',
    'Saint Peter\'s':'St. Peter\'s',
    'Arkansas St Red':'Arkansas State',
    'Southern Miss Golden':'Southern Miss',
    'Bowling Green':'Bowling Green State',
    'SE Missouri St':'Southeast Missouri State',
    'Cleveland St':'Cleveland State',
    'DePaul Blue':'DePaul',
    'Southern Indiana Screaming':'Southern Indiana',
    'Jackson St':'Jackson State',
    'Tenn-Martin':'UT-Martin',
    'Illinois St':'Illinois State',
    'Louisiana Ragin\'':'Louisiana',
    'Wichita St':'Wichita State',
    'Marquette Golden':'Marquette',
    'CSU Fullerton':'Cal State Fullerton',
    'Oklahoma St':'Oklahoma State',
    'Colorado St':'Colorado State',
    'Canisius Golden':'Canisius',
    'San José St':'San Jose State',
    'UC Riverside':'UC-Riverside',
    'Washington St':'Washington State',
    'Portland St':'Portland State',
    'CSU Bakersfield':'Cal State Bakersfield',
    'Delaware Blue':'Delaware',
    'Central Connecticut St Blue':'Central Connecticut',
    'St. Francis (PA) Red':'Saint Francis (PA)',
    'Pennsylvania':'Penn',
    'Alabama St':'Alabama State',
    'Cal Baptist':'California Baptist',
    'Nicholls St':'Nicholls State',
    'Alcorn St':'Alcorn State',
    'Loyola (Chi)':'Loyola (IL)',
    'Chicago St':'Chicago State',
    'UT Rio Grande Valley':'Texas-Rio Grande Valley',
    'Delaware St':'Delaware State',
    'Coppin St':'Coppin State',
    'Presbyterian Blue':'Presbyterian',
    'Albany Great':'Albany (NY)',
    'Boston Univ.':'Boston University',
    'Saint Joseph\'s':'St. Joseph\'s',
    'South Carolina Upstate':'USC Upstate',
    'Florida Int\'l Golden':'Florida International',
    'Evansville Purple':'Evansville',
    'Kansas St':'Kansas State',
    'Arizona St Sun':'Arizona State',
    'UC Davis':'UC-Davis',
    'Morgan St':'Morgan State',
    'Oral Roberts Golden':'Oral Roberts',
    'Oakland Golden':'Oakland',
    'San Diego St':'San Diego State',
    'UC San Diego':'UC-San Diego',
    'Jacksonville St':'Jacksonville State',
    'North Dakota St':'North Dakota State',
    'Montana St':'Montana State',
    'Niagara Purple':'Niagara',
    'Arkansas-Little Rock':'Little Rock',
    'Dartmouth Big':'Dartmouth',
    'Norfolk St':'Norfolk State',
    'UT-Arlington':'UT Arlington',
    'UC Santa Barbara':'UCSB',
    'Kennesaw St':'Kennesaw State',
    'Youngstown St':'Youngstown State',
    'New Mexico St':'New Mexico State',
    'UC Irvine':'UC-Irvine',
    'St. Thomas (MN)':'St. Thomas',
    'SE Louisiana':'Southeastern Louisiana',
    'Tennessee St':'Tennessee State',
    'Hawai\'i Rainbow':'Hawaii',
    'Grambling St':'Grambling',
    'UMKC':'Kansas City',
    'Northwestern St':'Northwestern State',
    'Cornell Big':'Cornell',
    'Fort Wayne':'Purdue Fort Wayne',
    'GW':'George Washington',
    'Mississippi St':'Mississippi State',
    'Queens University':'Queens (NC)',
    'Sacramento St':'Sacramento State',
    'Mt. St. Mary\'s':'Mount St. Mary\'s',
    'Fresno St':'Fresno State',
    'Long Beach St':'Long Beach State',
    'South Carolina St':'South Carolina State',
    'Miss Valley St Delta':'Mississippi Valley State',
    'N Colorado':'Northern Colorado',
    'UMass Lowell River':'UMass-Lowell',
    'Oregon St':'Oregon State',
    'Murray St':'Murray State',
    'East Tennessee St':'ETSU',
    'Arizona State Sun':'Arizona State',
    
}

soccer_codes = {
    'Atletico Paranaense':'Athletico Paranaense',
    'Atletico Goianiense':'Atlético Goianiense',
    'Criciuma':'Criciúma',
    'Sao Paulo':'São Paulo',
    'Vitoria':'Vitória',
    'Mirassol':'Mirassol Futebol Clube',
    'Qingdao West Coast FC':'Qingdao Kangtaiyuan FC',
    'Zhejiang':'Zhejiang Energy Greentown',
    'Shanghai SIPG FC':'Shanghai SIPG',
    'Beijing FC':'Beijing Sinobo Guoan',
    'Wuhan Three Towns':'Wuhan Three Towns FC',
    'Cangzhou Mighty Lions':'Shijiazhuang Ever Bright',
    'Chengdu Rongcheng FC':'Chengdu Better City FC',
    'Tianjin Jinmen Tiger FC':'Tianjin Jinmen Tiger',
    'Daejeon Citizen':'Daejeon Citizen FC',
    'Pohang Steelers':'Pohang',
    'Gangwon FC':'Gangwon',
    'Ulsan Hyundai FC':'Ulsan Hyundai',
    'Jeonbuk Hyundai Motors':'Jeonbuk',
    'Mazatlán FC':'Mazatlán',
    'Atlético San Luis':'Atlético',
    'Tigres':'UANL',
    'Sarpsborg FK':'Sarpsborg 08',
    'Bragantino-SP':'Red Bull Bragantino',
    'América Mineiro':'América (MG)',
    'Clube de Regatas Brasil':'CRB',
    'Shandong Luneng Taishan FC':'Shandong Luneng Taishan',
    'Henan FC':'Henan',
    'Qingdao Hainiu FC':'Qingdao Jonoon',
    'Shanghai Shenhua FC':'Shanghai Shenhua',
    'Shenzhen Peng City FC':'Sichuan',
    'Consadole Sapporo':'Hokkaido Consadole Sapporo',
    'Pumas':'Pumas UNAM',
    'Fredrikstad FK':'Fredrikstad',
    'KFUM':'KFUM Oslo',
    'Odds BK':'Odd',
    'Viking FK':'Viking',
    'Kristiansund BK':'Kristiansund',
    'Lillestrom':'Lillestrøm',
    'Stromsgodset':'Strømsgodset',
    'SK Brann':'Brann',
    'Tromso':'Tromsø',
    'Mjällby AIF':'Mjällby',
    'Malmo FF':'Malmö',
    'IK Sirius':'Sirius',
    'Montreal Impact':'CF Montréal',
    'Orlando City SC':'Orlando City',
    'Atlanta United FC':'Atlanta United',
    'St. Louis City SC':'St. Louis City',
    'Minnesota United FC':'Minnesota United',
    'Columbus Crew SC':'Columbus Crew',
    'Brusque FC':'Brusque Futebol Clube',
    'Avai':'Avaí',
    'FC Machida Zelvia':'Machida Zelvia',
    'Hiroshima Sanfrecce FC':'Sanfrecce Hiroshima',
    'Kyoto Purple Sanga':'Kyoto Sanga',
    'Jubilo Iwata':'Júbilo Iwata',
    'Yokohama F Marinos':'Yokohama F. Marinos',
    'Daegu FC':'Daegu',
    'Sangju Sangmu FC':'Sangju Sangmu',
    'Djurgardens IF':'Djurgården',
    'IFK Norrkoping':'Norrköping',
    'IFK Värnamo':'Värnamo',
    'IF Elfsborg':'Elfsborg',
    'BK Hacken':'Häcken',
    'Kalmar FF':'Kalmar',
    'Västerås SK':'Västerås',
    'IF Brommapojkarna':'Brommapojkarna',
    'Halmstads BK':'Halmstad',
    'IFK Goteborg':'Göteborg',
    'AIK':'AIK Stockholm',
    'Hammarby IF':'Hammarby',
    'Operario PR':'Operário',
    'Inter Miami CF':'Inter Miami',
    'Instituto de Córdoba':'Instituto',
    'CA Tigre BA':'Tigre',
    'Gimnasia La Plata':'Gimnasia y Esgrima (LP)',
    'Atlético Tucuman':'Atlético Tucumán',
    'Velez Sarsfield BA':'Vélez Sarsfield',
    'Central Córdoba':'Central Córdoba (SdE)',
    'Lanus':'Lanús',
    'Union Santa Fe':'Unión',
    'Belgrano de Cordoba':'Belgrano',
    'CD Cobreloa':'Cobreloa',
    'Brondby IF':'Brøndby',
    'Vejle Boldklub':'Vejle BK',
    'Raków Częstochowa':'RKS Raków',
    'Cracovia Kraków':'Cracovia',
    'Helsingborgs IF':'Helsingborg',
    'IK Oddevold':'Oddevold',
    'Östers IF':'Öster',
    'Örgryte IS':'Örgryte',
    'Qarabağ FK':'Qarabağ',
    'Lincoln Red Imps FC':'Lincoln Red Imps',
    'Petrocub Hîncești':'Petrocub Sărata-Galbenă',
    'APOEL FC':'APOEL',
    'Fenerbahce':'Fenerbahçe',
    'FC Lugano':'Lugano',
    'The New Saints FC':'The New Saints',
    'Ferencváros TC':'Ferencváros',
    'ŠK Slovan Bratislava':'Slovan Bratislava',
    'Klaksvíkar Ítróttarfelag':'KÍ',
    'FK RFS':'FK Rīgas FS',
    'FC Midtjylland':'Midtjylland',
    'FK Partizan':'Partizan',
    'Jagiellonia Białystok':'Jagiellonia',
    'FC Dinamo Minsk':'Dinamo Minsk',
    'PFC Ludogorets Razgrad':'Ludogorets Razgrad',
    'FK Borac Banja Luka':'Borac Banja Luka',
    'Fluminense-RJ':'Fluminense',
    'Clube Atlético Mineiro':'Atlético Mineiro',
    'Colo Colo':'Colo-Colo',
    'Junior FC':'Junior',
    'Peñarol Montevideo':'Peñarol',
    'Palmeiras-SP':'Palmeiras',
    'Club Atletico Talleres':'Talleres',
    'Viborg FF':'Viborg',
    'AaB':'Aalborg',
    'Stockport County FC':'Stockport',
    'Bromley FC':'Bromley',
    'Wimbledon':'AFC Wimbledon',
    'Rangers FC':'Rangers',
    'Union Saint-Gilloise':'Union SG',
    'Slavia Praha':'Slavia Prague',
    'LOSC Lille':'Lille',
    'FC Twente Enschede':'Twente',
    'Salzburg':'Red Bull Salzburg',
    'GIF Sundsvall':'Sundsvall',
    'Degerfors IF':'Degerfors',
    'Örebro SK':'Örebro',
    'Landskrona BoIS':'Landskrona',
    'GKS Katowice':'Katowice',
    'SJK Seinäjoki':'SJK',
    'Chesterfield FC':'Chesterfield',
    'Harrogate Town':'Harrogate',
    'Wrexham AFC':'Wrexham',
    'Flamengo-RJ':'Flamengo',
    'Club Bolívar':'Bolívar',
    'Athletic Bilbao':'Athletic Club',
    'Granada CF':'Granada',
    'FC Sheriff Tiraspol':'Sheriff Tiraspol',
    'Atlético Huracán':'Huracán',
    'Estudiantes':'Estudiantes (LP)',
    'Sarmiento de Junin':'Sarmiento',
    'Standard Liege':'Standard Liège',
    'Royal Antwerp':'Antwerp',
    'Leuven':'OH Leuven',
    'Cercle Brugge KSV':'Cercle Brugge',
    'KV Kortrijk':'Kortrijk',
    'Union La Calera':'La Calera',
    'Silkeborg IF':'Silkeborg',
    'Randers FC':'Randers',
    'SonderjyskE':'SønderjyskE',
    'FC Nordsjaelland':'Nordsjælland',
    'AGF Aarhus':'AGF',
    'RC Lens':'Lens',
    'Aris Thessaloniki':'Aris',
    'SC Bastia':'Bastia',
    'FC Martigues':'Martigues',
    'AS Roma':'Roma',
    'Atalanta BC':'Atalanta',
    'Cesena FC':'Cesena',
    'US Catanzaro 1929':'Catanzaro',
    'FC Zwolle':'Zwolle',
    'Panetolikos Agrinio':'Panetolikos',
    'Atromitos Athens':'Atromitos',
    'Asteras Tripolis':'Asteras Tripoli',
    'Athens Kallithea FC':'Kallithea',
    'Legia Warszawa':'Legia Warsaw',
    'Moreirense FC':'Moreirense',
    'Vitória SC':'Vitória Guimarães',
    'Boavista Porto':'Boavista',
    'CF Estrela':'Estrela',
    'Real Racing Club de Santander':'Racing Santander',
    'Burgos CF':'Burgos',
    'FC Cartagena':'Cartagena',
    'SD Huesca':'Huesca',
    'CD Eldense':'Eldense',
    'IK Brage':'Brage',
    'Basaksehir':'İstanbul Başakşehir',
    'Besiktas JK':'Beşiktaş',
    'Gazişehir Gaziantep':'Gaziantep FK',
    'Bodrum FK':'BB Bodrumspor',
    'Kasimpasa SK':'Kasımpaşa',
    'PAS Lamia 1964':'PAS Lamia',
    'FK TSC Bačka Topola':'TSC Bačka Top',
    'Panathinaikos FC':'Panathinaikos',
    'FC Pyunik':'Pyunik',
    'Newells Old Boys':'Newell\'s Old Boys',
    'Austria Klagenfurt':'SK Austria Klagenfurt',
    'FC Blau-Weiß Linz':'Blau-Weiß Linz',
    'KV Mechelen':'Mechelen',
    'Sint Truiden':'Sint-Truiden',
    'Luton':'Luton Town',
    'Brighton and Hove Albion':'Brighton & Hove Albion',
    'AS Monaco':'Monaco',
    'Saint Etienne':'Saint-Étienne',
    'Stade de Reims':'Reims',
    'Grenoble':'Grenoble Foot',
    'FSV Mainz 05':'Mainz 05',
    'TSG Hoffenheim':'Hoffenheim',
    'VfL Bochum':'Bochum',
    'SC Freiburg':'Freiburg',
    'VfB Stuttgart':'Stuttgart',
    'Borussia Dortmund':'Dortmund',
    'VfL Wolfsburg':'Wolfsburg',
    'FC St. Pauli':'St. Pauli',
    '1. FC Heidenheim':'Heidenheim',
    'SC Preußen Münster':'Preußen Münster',
    '1. FC Kaiserslautern':'Kaiserslautern',
    'SC Paderborn':'Paderborn 07',
    'Hertha Berlin':'Hertha BSC',
    '1. FC Köln':'Köln',
    '1. FC Magdeburg':'Magdeburg',
    'FC Schalke 04':'Schalke 04',
    '1. FC Nürnberg':'Nürnberg',
    'SV Darmstadt 98':'Darmstadt 98',
    'Fortuna Düsseldorf':'Düsseldorf',
    'SSV Ulm 1846':'Ulm',
    '1. FC Saarbrücken':'Saarbrücken',
    'FC Ingolstadt 04':'Ingolstadt 04',
    'Arminia Bielefeld':'Arminia',
    'Borussia Dortmund II':'Dortmund II',
    'SV Sandhausen':'Sandhausen',
    'VfL Osnabrück':'Osnabrück',
    'SpVgg Unterhaching':'Unterhaching',
    'FC Energie Cottbus':'Energie Cottbus',
    'Alemannia Aachen':'Aachen',
    'TSV 1860 München':'1860 Munich',
    'FC Viktoria Köln 1904':'Viktoria Köln',
    'SC Verl':'Verl',
    'Waldhof Mannheim':'SV Waldhof',
    'Panserraikos FC':'Panserraikos',
    'Volos FC':'Volos NFC',
    'PAOK Thessaloniki':'PAOK',
    'AC Milan':'Milan',
    'Inter Milan':'Internazionale',
    'FC Utrecht':'Utrecht',
    'FC Porto':'Porto',
    'Rio Ave FC':'Rio Ave',
    'Gil Vicente':'Gil Vicente FC',
    'AVS Futebol SAD':'AVS Futebol',
    'CA Osasuna':'Osasuna',
    'Racing de Ferrol':'Racing Ferrol',
    'Cádiz CF':'Cádiz',
    'CD Castellón':'Castellón',
    'Dundee FC':'Dundee',
    'Hearts':'Heart of Midlothian',
    'Çaykur Rizespor':'Rizespor',
    'Torku Konyaspor':'Konyaspor',
    'FC Basel':'Basel',
    'Grasshopper Zürich':'Grasshopper',
    'Yverdon Sport FC':'Yverdon-Sport',
    'FC Luzern':'Luzern',
    'FC Sion':'Sion',
    'Östersunds FK':'Östersund',
    'Trelleborgs FF':'Trelleborg',
    'Gefle IF':'Gefle',
    'Skövde AIK':'Skövde',
    'AC Ajaccio':'Ajaccio',
    'Olympiakos Piraeus':'Olympiacos',
    'Varbergs BoIS':'Varberg',
    'Utsiktens BK':'Utsikten',
    'Annecy FC':'Annecy',
    'Clermont':'Clermont Foot',
    'Rodez AF':'Rodez Aveyron',
    'USL Dunkerque':'Dunkerque',
    'Stade Lavallois':'Stade Laval',
    'Borussia Monchengladbach':'Mönchengladbach',
    'Dynamo Dresden':'Dresden',
    'VfB Stuttgart II':'Stuttgart II',
    'Sporting Lisbon':'Sporting CP',
    'BSC Young Boys':'Young Boys',
    'FC Lausanne-Sport':'Lausanne-Sport',
    'Goztepe':'Göztepe',
    'RB Salzburg':'Red Bull Salzburg',
    'Paris Saint Germain':'Paris Saint-Germain',
    'Karlsruher SC':'Karlsruher',
    'SC Farense':'Farense',
    'SD Eibar':'Eibar',
    'FC Zurich':'Zürich',
    'Servette':'Servette FC',
    'Turkey':'Türkiye',
    'Czech Republic':'Czechia',
    'Bosnia & Herzegovina':'Bosnia and Herzegovina',
    'Bayern München':'Bayern Munich',
    'Internazionale Milano':'Internazionale',
    'SK Sturm Graz':'Sturm Graz',
    'SS Lazio':'Lazio',
    'SC Braga':'Braga',
    'İstanbul Başakşehir FK':'İstanbul Başakşehir',
    'NK Olimpija Ljubljana':'Olimpija Ljubljana',
    'Zenit St Petersburg':'Zenit',
    'FC Astana':'Astana FK',
    'FK Mladá Boleslav':'Mladá Boleslav',
    'Molde FK':'Molde',
    'Omonoia FC':'AC Omonia',
    'Newcastle Jets FC':'Newcastle Jets',
    'Wellington Phoenix FC':'Wellington Phoenix',
    'Western United FC':'Western United',
    'FC St Gallen':'St. Gallen',
    'Atletico Mineiro':'Atlético Mineiro',
    'Víkingur Reykjavík':'KV',
    'FC St. Gallen':'St. Gallen',
    'Harrogate Town AFC':'Harrogate',
    'Gainsborough Trinity FC':'Gainsborough',
    'Wealdstone FC':'Wealdstone',
    'Brackley Town FC':'Brackley Town',
    'Walsall Wood FC':'Walsall',
    'Notts County FC':'Notts County',
    'Dagenham and Redbridge FC':'Dagenham & Redbridge',
    'Kettering Town FC':'Kettering Town',
    'Tamworth FC':'Tamworth',
    'Harborough Town FC':'Harborough',
    'Solihull Moors FC':'Solihull Moors',
    
}
